version: '3.8'

services:
  # --- 1. WEB PROXY (Nginx) ---
  proxy:
    image: nginx:1.25-alpine
    container_name: islamcoop-nginx
    restart: unless-stopped
#    ports:
#      - "80:80"
#      - "443:443"
    volumes:
      - ./backend:/var/www/html
      - ./frontend/dist:/var/www/html/public/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - islamcoop-network
      - gateway-network
    depends_on:
      app:
        condition: service_healthy

  # --- 2. PHP-FPM APP ---
  app:
    build:
      context: ./backend
      dockerfile: ../docker/php/Dockerfile
    container_name: attaqwa-app
    restart: unless-stopped
    working_dir: /var/www/html
    env_file: [ ".env" ]
    volumes:
      - ./backend:/var/www/html
    networks:
      - islamcoop-network
      - gateway-network
    healthcheck:
      test: ["CMD-SHELL", "php-fpm -t || exit 1"]
      interval: 30s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  # --- 3. QUEUE WORKER (Crucial for Paystack) ---
  worker:
    build:
      context: ./backend
      dockerfile: ../docker/php/Dockerfile
    container_name: islamcoop-worker
    restart: unless-stopped
    command: ["php", "artisan", "queue:work", "--tries=3", "--timeout=90"]
    env_file: [ ".env" ]
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    networks:
      - islamcoop-network
      - gateway-network
    depends_on:
      app:
        condition: service_started

  # --- 4. DATABASE ---
  db:
    image: mysql:8.4
    container_name: attaqwa-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - islamcoop-db-data:/var/lib/mysql
    networks:
      - islamcoop-network
      - gateway-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      interval: 10s
      retries: 5

  # --- 5. REDIS ---
  redis:
    image: redis:alpine
    container_name: attaqwa-redis
    restart: unless-stopped
    networks:
      - islamcoop-network
      - gateway-network



networks:
  islamcoop-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1350

volumes:
  islamcoop-db-data:
    driver: bridge
  gateway-network:
    external: true
