services:
  proxy:
    image: nginx:1.25-alpine
    container_name: assalaam-nginx
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html
      - ./frontend/dist:/var/www/html/public/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - assalam-network
      - gateway-network
    depends_on:
      - app
      - reverb

  app:
    build:
      context: ./backend
      dockerfile: ../docker/php/Dockerfile
    container_name: assalaam-app
    restart: unless-stopped
    env_file: [ ".env" ]
    volumes:
      - ./backend:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/99-custom.ini
    networks:
      - assalam-network
      - gateway-network
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.4
    container_name: assalaam-mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - assalam-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 180s

  redis:
    image: redis:alpine
    container_name: assalaam-redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-ANIbaba1122?}
    networks:
      - assalam-network

  worker:
    build:
      context: ./backend
      dockerfile: ../docker/php/Dockerfile
    container_name: assalaam-worker
    restart: unless-stopped
    command: php artisan horizon
    env_file: [ ".env" ]
    volumes:
      - ./backend:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/99-custom.ini
    networks:
      - assalam-network
      - gateway-network
    depends_on:
      - mysql
      - app

  reverb:
    build:
      context: ./backend
      dockerfile: ../docker/php/Dockerfile
    container_name: assalaam-reverb
    restart: unless-stopped
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    env_file: [ ".env" ]
    volumes:
      - ./backend:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/99-custom.ini
    networks:
      - assalam-network
      - gateway-network
    depends_on:
      - app

networks:
  assalam-network:
    driver: bridge
  gateway-network:
    external: true

volumes:
  mysql-data:
    driver: local
